services:
  - type: web
    name: khamen
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: CORS_ORIGIN
        value: https://saleh4dev.github.io,https://saleh4dev.github.io/khamen
      - key: NODE_VERSION
        value: "20"
      - key: VITE_SERVER_URL
        value: https://khamen.onrender.com
      - key: VITE_BASE
        value: /
